
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

GET {{host}}/candidates
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2VsdWlzQGV4YW1wbGUuY29tIiwicm9sZSI6ImNhbmRpZGF0ZSIsImlhdCI6MTY4NTQ0ODY0OX0.eBbOHUgKvZcN72lZWq1QC1FKHz_WfP-02wQPuetjHXo

### LOGIN CANDIDATES
POST {{host}}/candidates/signin 
Content-Type: application/json

{
  "email": "joseluis@example.com",
  "password": "123454523"
}

### Crear un nuevo Candidato
POST {{host}}/candidates
Content-Type: application/json

{
 "nombre": "Jose Luis",
  "email": "joseluis@example.com",
  "password": "123454523",
  "habilidades": "SQL",
  "ubicacion": "Sevilla",
  "educacion": "Bootcamp Full Stack",
  "experiencia": "1 año Junior Backend "
 }


### Obtener un candidato por ID
GET {{host}}/candidates/647099205606c749a80c22cd
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2VsdWlzQGV4YW1wbGUuY29tIiwicm9sZSI6ImNhbmRpZGF0ZSIsImlhdCI6MTY4NTQ0ODY0OX0.eBbOHUgKvZcN72lZWq1QC1FKHz_WfP-02wQPuetjHXo


### Dar like a una oferta
POST {{host}}/candidates/64709c1c9180fd76a9a2efa9/likes/646fa60fae7df8187024170b



### Ver todas las ofertas de un candidato
GET {{host}}/candidates/6475d9602f50ca540eb7e37d/offers