
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

GET {{host}}/candidates


###
POST {{host}}/candidates
Content-Type: application/json

{
 "nombre": "Benjy",
  "email": "benjy@example.com",
  "password": "1234545",
  "habilidades": "React",
  "ubicacion": "Sevilla",
  "educacion": "Bootcamp Full Stack",
  "experiencia": "4 años Junior Frontend "
 }

###
GET {{host}}/candidates/646f81f07ab99045006a5a3e
