
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

### Obtener las empresas
GET {{host}}/companies

### Crear una nueva empresa

POST {{host}}/companies
Content-Type: application/json

{
    "nombre": "The Bridge",
"email": "thebridge@gmail.com",
"contraseña": "thebridge",
"ubicacion": "Madrid",
"descripcion": "Aceleradora de Talento y Tecnologica"

}

### Obtener empresa por ID
GET {{host}}/companies/64709ca89180fd76a9a2efbd

### Ver Ofertas de una empresa
GET {{host}}/companies/64709ca89180fd76a9a2efbd/offers
