
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

### Obtener las ofertas
GET {{host}}/offers

### Crear una nueva oferta 
POST {{host}}/offers
Content-Type: application/json

{
  "empresaId": "64709ca89180fd76a9a2efbd",
  "titulo": "OFERTA PARA ELIMINAR",
  "descripcion": "Teacher Assistant en The Bridge para el Bootcamp Data Science",
  "requisitos": "Titulación Data Science en The Bridge"
}

### Modificar una Oferta
PUT {{host}}/offers/64709d2d9180fd76a9a2efc7
Content-Type: application/json

{
    "empresaId": "64709ca89180fd76a9a2efbd",
  "titulo": "URGENTE! Teacher Assistant Data Science",
  "descripcion": "Teacher Assistant en The Bridge para el Bootcamp Data Science",
  "requisitos": "Titulación Data Science en The Bridge"

}

### Eliminar una Oferta
DELETE {{host}}/offers/64733d8ce34748a0cb4ba41a

### Ver los candidatos de una oferta
GET {{host}}/offers/646f9784884e99616d54b714/candidates

### MATCH
POST {{host}}/offers/check-match
Content-Type: application/json

{
  "candidateId": "64709c1c9180fd76a9a2efa9",
  "offerId": "646f9784884e99616d54b714"
}